
import 'package:flutter/cupertino.dart';

class County {

  String name;
  String link;
  String detail;

  County(String currentName){

    this.name = currentName;
    this.link = 'https://en.wikipedia.org/wiki/${this.name}_County,_Florida';
    this.detail = County.countiesMap[this.name];
  }

  static Map<String, String> countiesMap = {'Alachua': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
  
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Baker': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Bay': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Bradford' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Brevard' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Broward' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''' ,
    'Calhoun' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''' ,
    'Charlotte' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Citrus' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Clay': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Collier': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Columbia': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Dade' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Desoto' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Dixie' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Duval' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Escambia' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''' ,
    'Flagler' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Franklin': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Gadsden': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Gilchrist': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Glades': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Gulf': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Hamilton': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Hardee' : '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Hendry': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Hernando': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Highlands': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Hillsborough': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Holmes': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Indian River': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Jackson': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Jefferson': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Lafayette': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Lake': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Lee': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Leon': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Levy': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Liberty': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Madison': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Manatee': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Marion': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Martin': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Miami-Dade': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Monroe': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Multiple Counties': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Nassau': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Okaloosa': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Okeechobee': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Orange': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Osceola': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Palm Beach': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Pasco': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Pinellas': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Polk': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Putnam': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Santa Rosa': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Sarasota': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Seminole': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'St. Johns': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'St. Lucie': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Sumter': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Suwannee': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Taylor': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Union': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Volusia': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Wakulla': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Walton': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.''',
    'Washington': '''Jackson County was created by the Florida Territorial Council in 1822 out of Escambia County, at the same time that Duval County was organized from land of St. Johns County, making them the third and fourth counties in the Territory. The county was named for Andrew Jackson, a General of the War of 1812, who had served as Florida's first military governor for six months in 1821.[4] Jackson County originally extended from the Choctawhatchee River on the west to the Suwannee River on the east. By 1840 the county had been reduced close to its present boundaries through the creation of new counties from its original territory, following an increase of population in these areas. Minor adjustments to the county boundaries continued through most of the 19th century, however.
There were no towns in Jackson County when it was formed. The first county court met at what was called "Robinson's Big Spring" (later called Blue Springs) in 1822 and then at the "Big Spring of the Choctawhatchee" in 1823. The following year the county court met at "Chipola Settlement", which is also known as Waddell's Mill Pond.'''};

  Map<String, String> LinkMap = {'Alachua': ''' ''',
    'Baker': ''' ''',
    'Bay': ''' ''',
    'Bradford' : ''' ''',
    'Brevard' : ''' ''',
    'Broward' : ''' ''' ,
    'Calhoun' : ''' ''' ,
    'Charlotte' : ''' ''',
    'Citrus' : ''' ''',
    'Clay': ''' ''',
    'Collier': ''' ''',
    'Columbia': ''' ''',
    'Dade' : ''' ''',
    'Desoto' : ''' ''',
    'Dixie' : ''' ''',
    'Duval' : ''' ''',
    'Escambia' : ''' ''' ,
    'Flagler' : ''' ''',
    'Franklin': ''' ''',
    'Gadsden': ''' ''',
    'Gilchrist': ''' ''',
    'Glades': ''' ''',
    'Gulf': ''' ''',
    'Hamilton': ''' ''',
    'Hardee' : ''' ''',
    'Hendry': ''' ''',
    'Hernando': ''' ''',
    'Highlands': ''' ''',
    'Hillsborough': ''' ''',
    'Holmes': ''' ''',
    'Indian River': ''' ''',
    'Jackson': ''' ''',
    'Jefferson': ''' ''',
    'Lafayette': ''' ''',
    'Lake': ''' ''',
    'Lee': ''' ''',
    'Leon': ''' ''',
    'Levy': ''' ''',
    'Liberty': ''' ''',
    'Madison': ''' ''',
    'Manatee': ''' ''',
    'Marion': ''' ''',
    'Martin': ''' ''',
    'Miami-Dade': ''' ''',
    'Monroe': ''' ''',
    'Multiple Counties': ''' ''',
    'Nassau': ''' ''',
    'Okaloosa': ''' ''',
    'Okeechobee': ''' ''',
    'Orange': ''' ''',
    'Osceola': ''' ''',
    'Palm Beach': ''' ''',
    'Pasco': ''' ''',
    'Pinellas': ''' ''',
    'Polk': ''' ''',
    'Putnam': ''' ''',
    'Santa Rosa': ''' ''',
    'Sarasota': ''' ''',
    'Seminole': ''' ''',
    'St. Johns': ''' ''',
    'St. Lucie': ''' ''',
    'Sumter': ''' ''',
    'Suwannee': ''' ''',
    'Taylor': ''' ''',
    'Union': ''' ''',
    'Volusia': ''' ''',
    'Wakulla': ''' ''',
    'Walton': ''' ''',
    'Washington': ''' '''};


}